import '../../../../data/model/province/province_model.dart';

List<Province> listProvinsi = [
  const Province(id: '1', name: 'Aceh'),
  const Province(id: '2', name: 'Sumatera Utara'),
  const Province(id: '3', name: 'Sumatera Barat'),
  const Province(id: '4', name: 'Riau'),
  const Province(id: '5', name: 'Kepulauan Riau'),
  const Province(id: '6', name: 'Jambi'),
  const Province(id: '7', name: 'Bengkulu'),
  const Province(id: '8', name: 'Sumatera Selatan'),
  const Province(id: '9', name: 'Kepulauan Bangka Belitung'),
  const Province(id: '10', name: 'Lampung'),
  const Province(id: '11', name: 'DKI Jakarta'),
  const Province(id: '12', name: 'Banten'),
  const Province(id: '13', name: 'Jawa Barat'),
  const Province(id: '14', name: 'Jawa Tengah'),
  const Province(id: '15', name: 'DI Yogyakarta'),
  const Province(id: '16', name: 'Jawa Timur'),
  const Province(id: '17', name: 'Bali'),
  const Province(id: '18', name: 'Nusa Tenggara Barat'),
  const Province(id: '19', name: 'Nusa Tenggara Timur'),
  const Province(id: '20', name: 'Kalimantan Barat'),
  const Province(id: '21', name: 'Kalimantan Tengah'),
  const Province(id: '22', name: 'Kalimantan Selatan'),
  const Province(id: '23', name: 'Kalimantan Timur'),
  const Province(id: '24', name: 'Kalimantan Utara'),
  const Province(id: '25', name: 'Sulawesi Utara'),
  const Province(id: '26', name: 'Gorontalo'),
  const Province(id: '27', name: 'Sulawesi Tengah'),
  const Province(id: '28', name: 'Sulawesi Selatan'),
  const Province(id: '29', name: 'Sulawesi Barat'),
  const Province(id: '30', name: 'Sulawesi Tenggara'),
  const Province(id: '31', name: 'Maluku'),
  const Province(id: '32', name: 'Maluku Utara'),
  const Province(id: '33', name: 'Papua'),
  const Province(id: '34', name: 'Papua Barat'),
  const Province(id: '35', name: 'Papua Tengah'),
  const Province(id: '36', name: 'Papua Pegunungan'),
  const Province(id: '37', name: 'Papua Selatan'),
  const Province(id: '38', name: 'Papua Barat Daya'),
];
